; PlatformIO Project Configuration File
;
; watchorugabasz — Comunicacion ESP-NOW entre T-Watch y XIAO ESP32-C3
;
; Dos entornos:
;   lilyorugabasz → T-Watch 2020 V2 (emisor, botones ON/OFF)
;   orugabasz     → XIAO ESP32-C3 (receptor, controla LED)

[env:lilyorugabasz]
platform = espressif32
board = ttgo-t-watch
framework = arduino
upload_port = COM13
monitor_port = COM13
monitor_speed = 115200
build_src_filter = +<lilyorugabasz/>
build_flags = -Wno-discarded-qualifiers
lib_extra_dirs = ${PROJECT_DIR}/../lilygosz/lib

[env:orugabasz]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
upload_port = COM4
monitor_port = COM4
monitor_speed = 115200
build_src_filter = +<orugabasz/>
